# Generated by Django 3.2.25 on 2024-04-03 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0002_auto_20240403_0509'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverychellan',
            name='balance',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='deliverychellan',
            name='to_inv',
            field=models.CharField(blank=True, default='Convert to invoice', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='deliverychellan',
            name='to_recinv',
            field=models.CharField(blank=True, default='Convert to reccuring invoice', max_length=100, null=True),
        ),
    ]
