# Generated by Django 3.2.25 on 2024-04-03 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0003_auto_20240403_0509'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor_credits_bills',
            name='acc_no',
        ),
        migrations.RemoveField(
            model_name='vendor_credits_bills',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='vendor_credits_bills',
            name='bill_number',
        ),
        migrations.RemoveField(
            model_name='vendor_credits_bills',
            name='cheque',
        ),
        migrations.RemoveField(
            model_name='vendor_credits_bills',
            name='paid',
        ),
        migrations.RemoveField(
            model_name='vendor_credits_bills',
            name='payment_methode',
        ),
        migrations.RemoveField(
            model_name='vendor_credits_bills',
            name='shipping_charge',
        ),
        migrations.RemoveField(
            model_name='vendor_credits_bills',
            name='status',
        ),
        migrations.RemoveField(
            model_name='vendor_credits_bills',
            name='upi',
        ),
    ]
